LGV_TZ_Lookup: /Users/chrismarshall/Developer/LGV/LGV_TZ_Lookup/src/vendor/salsify/json-streaming-parser/example/example.php File Reference
example.php File Reference
Variables
$testfile = __DIR__.'/../tests/data/example.json'
$listener = new \JsonStreamingParser\Listener\InMemoryListener()
$stream = fopen($testfile, 'r')
try
Variable Documentation
$listener
$listener = new \JsonStreamingParser\Listener\InMemoryListener()
Definition at line 9 of file example.php.
Referenced by Parser\__construct(), and call_server().
$stream
$stream = fopen($testfile, 'r')
Definition at line 10 of file example.php.
Referenced by Parser\__construct(), and call_server().
$testfile
$testfile = __DIR__.'/../tests/data/example.json'
Definition at line 7 of file example.php.
try
try
Initial value:
{
    $parser = new \JsonStreamingParser\Parser($stream, $listener)
Definition at line 11 of file example.php.