LGV_TZ_Lookup: RegexListener Class Reference
RegexListener Class Reference
Inherits ListenerInterface.
Public Member Functions
__construct (array $dataMatch=[])
setMatch (array $dataMatch)
startObject ($index=self::OBJECT)
endObject ()
startArray ()
endArray ()
whitespace (string $whitespace)
startDocument ()
endDocument ()
value ($value)
key (string $key)
Public Member Functions inherited from ListenerInterface
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
Data Fields
const OBJECT = -1
const ARRAY = 0
Private Member Functions
getPath ()
Private Attributes
$dataMatch
$path = []
$pathIndex = []
$pathLength = 0
$stack = []
$label
$levelInterest = PHP_INT_MAX
$complete = false
$objectEncountered = false
Detailed Description
Allow to select elements from a JSON being loaded via a regex expression. As the JSON is loaded you can use expressions such as /name to select a name attribute from the root of the document. For arrays, /1/name which is the name element from the second element of an array. Using things like /\d* will match any array element.
Basic usage (with file tests/data/example.json): $listener = new RegexListener(["/1/name" => function ($data) { echo "/1/name=".$data.PHP_EOL; }]); $parser = new Parser(fopen($filename, 'rb'), $listener); $parser->parse();
Capture groups can also be used to provide the element path to the data located, so (/\d*) will pass the array element number along with the element value.
Example using capture groups: $listener = new RegexListener(["(/\d*)" => function ($data, $path) { echo $path."=".$data['name'].PHP_EOL; }]); $parser = new Parser(fopen($filename, 'rb'), $listener); $parser->parse();
It's also possible to stop the load if you only need specific data.
Example to stop read (with file tests/data/ratherBig.json): $listener = new RegexListener(); $parser = new Parser(fopen($filename, 'rb'), $listener); $listener->setMatch(["/total_rows" => function ($data) use ($parser) { echo "/total_rows=".$data.PHP_EOL; $parser->stop(); }]);
Author
NigelRen nigel.nosp@m.rel3.nosp@m.@yaho.nosp@m.o.co.nosp@m..uk
Definition at line 44 of file RegexListener.php.
Constructor & Destructor Documentation
__construct()
__construct (array $dataMatch = [])
Parameters
array $dataMatch - [regex => closure()] format
Definition at line 131 of file RegexListener.php.
    {
        $this->setMatch($dataMatch);
    }
References RegexListener\$dataMatch, and RegexListener\setMatch().
Member Function Documentation
endArray()
endArray ()
Implements ListenerInterface.
Definition at line 211 of file RegexListener.php.
                              : void
    {
        $this->endObject();
    }
References RegexListener\endObject().
endDocument()
endDocument ()
Implements ListenerInterface.
Definition at line 225 of file RegexListener.php.
                                 : void
    {
        $this->complete = true;
    }
endObject()
endObject ()
Implements ListenerInterface.
Definition at line 187 of file RegexListener.php.
                               : void
    {
        $obj = array_pop($this->stack);
        if ($this->pathLength > 0) {
            $this->label = array_pop($this->path);
            $this->value($obj);
            array_pop($this->pathIndex);
            $this->pathLength--;
        } else {
            $this->value($obj);
        }
        // Update array index if neccessary.
        if ($this->pathLength > 0
            && $this->pathIndex[$this->pathLength - 1] !== self::OBJECT
        ) {
            $this->pathIndex[$this->pathLength - 1]++;
        }
    }
References RegexListener\value().
Referenced by RegexListener\endArray().
getPath()
getPath () private
Returns the path at the current element. This is made up of both the path (including array indicies) to this point as well as the current label(if set).
Definition at line 277 of file RegexListener.php.
                              : string
    {
        $path = '';
        foreach ($this->path as $key => $pathElement) {
            if (!empty($pathElement)) {
                $path .= '/'.$pathElement;
            }
            // Add in array index if present
            if ($this->pathIndex[$key] !== self::OBJECT) {
                $path .= '/'.$this->pathIndex[$key];
            }
        }
        // Add in current label if present
        if ($this->label) {
            $path .= '/'.$this->label;
        }
        return $path;
    }
References RegexListener\$path.
Referenced by RegexListener\startObject(), and RegexListener\value().
key()
key (string $key)
Implements ListenerInterface.
Definition at line 267 of file RegexListener.php.
                                    : void
    {
        $this->label = $key;
    }
setMatch()
setMatch (array $dataMatch)
Sets the combination of regex and closures to be processed against the JSON input. Sent as [regex => closure()] format.
Definition at line 141 of file RegexListener.php.
                                              : void
    {
        $this->dataMatch = $dataMatch;
    }
References RegexListener\$dataMatch.
Referenced by RegexListener\__construct().
startArray()
startArray ()
Implements ListenerInterface.
Definition at line 206 of file RegexListener.php.
                                : void
    {
        $this->startObject(self::ARRAY);
    }
References ListenerInterface\startObject().
startDocument()
startDocument ()
Implements ListenerInterface.
Definition at line 220 of file RegexListener.php.
                                   : void
    {
        $this->complete = false;
    }
startObject()
startObject ($index = self::OBJECT)
{}
See also
\JsonStreamingParser\Listener\ListenerInterface::startObject()
Parameters
int $index - set to 0 for arrays (used for index number)
Definition at line 153 of file RegexListener.php.
                                                    : void
    {
        // Does the hierarchy need updating?
        if ($index !== self::OBJECT
            || $this->pathLength !== 0
            || !empty($this->label)
        ) {
            $this->path[] = $this->label ?? '';
            $this->pathIndex[] = $index;
            $this->pathLength++;
        }
        $this->stack[] = [];
        $this->label = null;
        // If not already interested in the data, check if it is now.
        if ($this->levelInterest === PHP_INT_MAX) {
            $path = $this->getPath();
            foreach (array_keys($this->dataMatch) as $pathReg) {
                // Check if matches regex, if this is an array, then check
                // if matches with regex/0 when looking at first element.
                if (preg_match('#^'.$pathReg.'$#', $path)
                    || (preg_match('#^'.$pathReg.'/0$#', $path)
                        && $this->pathIndex[$this->pathLength - 1] === 0
                    )
                ) {
                    $this->levelInterest = $this->pathLength;
                }
            }
        }
        // Set object flag (Only when processing objects and not arrays).
        $this->objectEncountered = ($index === self::OBJECT);
    }
References RegexListener\$path, RegexListener\$pathLength, RegexListener\getPath(), and RegexListener\OBJECT.
value()
value ($value)
Parameters
mixed $value the value as read from the parser, it may be a string, integer, boolean, etc
Implements ListenerInterface.
Definition at line 230 of file RegexListener.php.
                                 : void
    {
        $obj = array_pop($this->stack);
        $path = $this->getPath();
        // Check the path against the required matches
        foreach ($this->dataMatch as $pathReg => $closure) {
            $matches = [];
            if (preg_match('#^'.$pathReg.'$#', $path, $matches)) {
                $closure($value, $matches[1] ?? []);
            }
        }
        if ($this->label !== null) {
            $obj[$this->label] = $value;
            $this->label = null;
        } else {
            $obj[] = $value;
        }
        // Check if need to store the data
        if ($this->levelInterest <= $this->pathLength) {
            $this->stack[] = $obj;
        } else {
            $this->levelInterest = PHP_INT_MAX;
        }
        // Update array index if neccessary.
        if ($this->objectEncountered === false
            && $this->pathLength > 0
            && $this->pathIndex[$this->pathLength - 1] !== self::OBJECT
        ) {
            $this->pathIndex[$this->pathLength - 1]++;
        }
        $this->objectEncountered = false;
    }
References RegexListener\$label, RegexListener\$path, and RegexListener\getPath().
Referenced by RegexListener\endObject().
whitespace()
whitespace (string $whitespace)
Implements ListenerInterface.
Definition at line 216 of file RegexListener.php.
                                                  : void
    {
    }
Field Documentation
$complete
$complete = false private
Definition at line 117 of file RegexListener.php.
$dataMatch
$dataMatch private
Definition at line 64 of file RegexListener.php.
Referenced by RegexListener\__construct(), and RegexListener\setMatch().
$label
$label private
Definition at line 101 of file RegexListener.php.
Referenced by RegexListener\value().
$levelInterest
$levelInterest = PHP_INT_MAX private
Definition at line 110 of file RegexListener.php.
$objectEncountered
$objectEncountered = false private
Definition at line 126 of file RegexListener.php.
$path
$path = [] private
Definition at line 71 of file RegexListener.php.
Referenced by RegexListener\getPath(), RegexListener\startObject(), and RegexListener\value().
$pathIndex
$pathIndex = [] private
Definition at line 79 of file RegexListener.php.
$pathLength
$pathLength = 0 private
Definition at line 86 of file RegexListener.php.
Referenced by RegexListener\startObject().
$stack
$stack = [] private
Definition at line 94 of file RegexListener.php.
ARRAY
const ARRAY = 0
Definition at line 57 of file RegexListener.php.
OBJECT
const OBJECT = -1
Definition at line 51 of file RegexListener.php.
Referenced by RegexListener\startObject().