LGV_TZ_Lookup: GeoJsonListener Class Reference
GeoJsonListener Class Reference
Inherits ListenerInterface.
Inherited by LGV_TZ_Lookup_Loader.
Public Member Functions
__construct ($callback=null)
getJson ()
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
Protected Attributes
$json
$stack
$key
$level
$callback
Detailed Description
This basic geojson implementation of a listener simply constructs an in-memory representation of the JSON document at the second level, this is useful so only a single Feature will be kept in memory rather than the whole FeatureCollection.
Definition at line 12 of file GeoJsonListener.php.
Constructor & Destructor Documentation
__construct()
__construct ($callback = null)
Parameters
callable $callback
Reimplemented in LGV_TZ_Lookup_Loader.
Definition at line 30 of file GeoJsonListener.php.
    {
        $this->callback = $callback;
    }
References GeoJsonListener\$callback.
Member Function Documentation
endArray()
endArray ()
Implements ListenerInterface.
Definition at line 86 of file GeoJsonListener.php.
                              : void
    {
        $this->endObject();
    }
References GeoJsonListener\endObject().
endDocument()
endDocument ()
Implements ListenerInterface.
Definition at line 49 of file GeoJsonListener.php.
                                 : void
    {
        // w00t!
    }
endObject()
endObject ()
Implements ListenerInterface.
Definition at line 65 of file GeoJsonListener.php.
                               : void
    {
        $this->level--;
        $obj = array_pop($this->stack);
        if (empty($this->stack)) {
            // doc is DONE!
            $this->json = $obj;
        } else {
            $this->value($obj);
        }
        // Call the callback when returning to the second level
        if (2 === $this->level && \is_callable($this->callback)) {
            \call_user_func($this->callback, $this->json);
        }
    }
References GeoJsonListener\value().
Referenced by GeoJsonListener\endArray().
getJson()
getJson ()
Definition at line 35 of file GeoJsonListener.php.
    {
        return $this->json;
    }
References GeoJsonListener\$json.
key()
key (string $key)
Implements ListenerInterface.
Definition at line 91 of file GeoJsonListener.php.
                                    : void
    {
        $this->key[$this->level] = $key;
    }
References GeoJsonListener\$key, GeoJsonListener\$level, and GeoJsonListener\key().
Referenced by GeoJsonListener\key(), GeoJsonListener\startDocument(), GeoJsonListener\startObject(), and GeoJsonListener\value().
startArray()
startArray ()
Implements ListenerInterface.
Definition at line 81 of file GeoJsonListener.php.
                                : void
    {
        $this->startObject();
    }
References GeoJsonListener\startObject().
startDocument()
startDocument ()
Implements ListenerInterface.
Definition at line 40 of file GeoJsonListener.php.
                                   : void
    {
        $this->stack = [];
        $this->level = 0;
        // Key is an array so that we can can remember keys per level to avoid
        // it being reset when processing child keys.
        $this->key = [];
    }
References GeoJsonListener\key().
startObject()
startObject ()
Implements ListenerInterface.
Definition at line 54 of file GeoJsonListener.php.
                                 : void
    {
        $this->level++;
        $this->stack[] = [];
        // Reset the stack when entering the second level
        if (2 === $this->level) {
            $this->stack = [];
            $this->key[$this->level] = null;
        }
    }
References GeoJsonListener\$level, and GeoJsonListener\key().
Referenced by GeoJsonListener\startArray().
value()
value ($value)
Value may be a string, integer, boolean, null.
Implements ListenerInterface.
Definition at line 99 of file GeoJsonListener.php.
                                 : void
    {
        $obj = array_pop($this->stack);
        if (!empty($this->key[$this->level])) {
            $obj[$this->key[$this->level]] = $value;
            $this->key[$this->level] = null;
        } else {
            $obj[] = $value;
        }
        $this->stack[] = $obj;
    }
References GeoJsonListener\$level, and GeoJsonListener\key().
Referenced by GeoJsonListener\endObject().
whitespace()
whitespace (string $whitespace)
Implements ListenerInterface.
Definition at line 111 of file GeoJsonListener.php.
                                                  : void
    {
    }
Field Documentation
$callback
$callback protected
Definition at line 25 of file GeoJsonListener.php.
Referenced by GeoJsonListener\__construct().
$json
$json protected
Definition at line 14 of file GeoJsonListener.php.
Referenced by GeoJsonListener\getJson().
$key
$key protected
Definition at line 17 of file GeoJsonListener.php.
Referenced by GeoJsonListener\key().
$level
$level protected
Definition at line 20 of file GeoJsonListener.php.
Referenced by GeoJsonListener\key(), GeoJsonListener\startObject(), and GeoJsonListener\value().
$stack
$stack protected
Definition at line 16 of file GeoJsonListener.php.