LGV_TZ_Lookup: ClassLoader Class Reference
ClassLoader Class Reference
Public Member Functions
__construct ($vendorDir=null)
getPrefixes ()
getPrefixesPsr4 ()
getFallbackDirs ()
getFallbackDirsPsr4 ()
getClassMap ()
addClassMap (array $classMap)
add ($prefix, $paths, $prepend=false)
addPsr4 ($prefix, $paths, $prepend=false)
set ($prefix, $paths)
setPsr4 ($prefix, $paths)
setUseIncludePath ($useIncludePath)
getUseIncludePath ()
setClassMapAuthoritative ($classMapAuthoritative)
isClassMapAuthoritative ()
setApcuPrefix ($apcuPrefix)
getApcuPrefix ()
register ($prepend=false)
unregister ()
loadClass ($class)
findFile ($class)
Static Public Member Functions
static getRegisteredLoaders ()
Private Member Functions
findFileWithExtension ($class, $ext)
Static Private Member Functions
static initializeIncludeClosure ()
Private Attributes
$vendorDir
$prefixLengthsPsr4 = array()
$prefixDirsPsr4 = array()
$fallbackDirsPsr4 = array()
$prefixesPsr0 = array()
$fallbackDirsPsr0 = array()
$useIncludePath = false
$classMap = array()
$classMapAuthoritative = false
$missingClasses = array()
$apcuPrefix
Static Private Attributes
static $includeFile
static $registeredLoaders = array()
Detailed Description
ClassLoader implements a PSR-0, PSR-4 and classmap class loader.
$loader = new \Composer\Autoload\ClassLoader();
// register classes with namespaces
$loader->add('Symfony\Component', __DIR__.'/component');
$loader->add('Symfony',           __DIR__.'/framework');
// activate the autoloader
$loader->register();
// to enable searching the include path (eg. for PEAR packages)
$loader->setUseIncludePath(true);
In this example, if you try to use a class in the Symfony\Component namespace or one of its children (Symfony\Component\Console for instance), the autoloader will first look for the class under the component/ directory, and it will then fallback to the framework/ directory if not found before giving up.
This class is loosely based on the Symfony UniversalClassLoader.
Author
Fabien Potencier fabie.nosp@m.n@sy.nosp@m.mfony.nosp@m..com
Jordi Boggiano j.bog.nosp@m.gian.nosp@m.o@sel.nosp@m.d.be
See also
https://www.php-fig.org/psr/psr-0/
https://www.php-fig.org/psr/psr-4/
Definition at line 43 of file ClassLoader.php.
Constructor & Destructor Documentation
__construct()
__construct ($vendorDir = null)
Parameters
string | null $vendorDir
Definition at line 106 of file ClassLoader.php.
    {
        $this->vendorDir = $vendorDir;
        self::initializeIncludeClosure();
    }
References ClassLoader\$vendorDir, and ClassLoader\initializeIncludeClosure().
Member Function Documentation
add()
add ($prefix, $paths, $prepend = false)
Registers a set of PSR-0 directories for a given prefix, either appending or prepending to the ones previously set for this prefix.
Parameters
string $prefix The prefix
list<string>|string $paths The PSR-0 root directories
bool $prepend Whether to prepend the directories
Returns
void
Definition at line 180 of file ClassLoader.php.
    {
        $paths = (array) $paths;
        if (!$prefix) {
            if ($prepend) {
                $this->fallbackDirsPsr0 = array_merge(
                    $paths,
                    $this->fallbackDirsPsr0
                );
            } else {
                $this->fallbackDirsPsr0 = array_merge(
                    $this->fallbackDirsPsr0,
                    $paths
                );
            }
            return;
        }
        $first = $prefix[0];
        if (!isset($this->prefixesPsr0[$first][$prefix])) {
            $this->prefixesPsr0[$first][$prefix] = $paths;
            return;
        }
        if ($prepend) {
            $this->prefixesPsr0[$first][$prefix] = array_merge(
                $paths,
                $this->prefixesPsr0[$first][$prefix]
            );
        } else {
            $this->prefixesPsr0[$first][$prefix] = array_merge(
                $this->prefixesPsr0[$first][$prefix],
                $paths
            );
        }
    }
addClassMap()
addClassMap (array $classMap)
Parameters
array<string,string> $classMap Class to filename map
Returns
void
Definition at line 161 of file ClassLoader.php.
    {
        if ($this->classMap) {
            $this->classMap = array_merge($this->classMap, $classMap);
        } else {
            $this->classMap = $classMap;
        }
    }
References ClassLoader\$classMap.
addPsr4()
addPsr4 ($prefix, $paths, $prepend = false)
Registers a set of PSR-4 directories for a given namespace, either appending or prepending to the ones previously set for this namespace.
Parameters
string $prefix The prefix/namespace, with trailing '\'
list<string>|string $paths The PSR-4 base directories
bool $prepend Whether to prepend the directories
Exceptions
InvalidArgumentException
Returns
void
Definition at line 230 of file ClassLoader.php.
    {
        $paths = (array) $paths;
        if (!$prefix) {
            // Register directories for the root namespace.
            if ($prepend) {
                $this->fallbackDirsPsr4 = array_merge(
                    $paths,
                    $this->fallbackDirsPsr4
                );
            } else {
                $this->fallbackDirsPsr4 = array_merge(
                    $this->fallbackDirsPsr4,
                    $paths
                );
            }
        } elseif (!isset($this->prefixDirsPsr4[$prefix])) {
            // Register directories for a new namespace.
            $length = strlen($prefix);
            if ('\\' !== $prefix[$length - 1]) {
                throw new \InvalidArgumentException("A non-empty PSR-4 prefix must end with a namespace separator.");
            }
            $this->prefixLengthsPsr4[$prefix[0]][$prefix] = $length;
            $this->prefixDirsPsr4[$prefix] = $paths;
        } elseif ($prepend) {
            // Prepend directories for an already registered namespace.
            $this->prefixDirsPsr4[$prefix] = array_merge(
                $paths,
                $this->prefixDirsPsr4[$prefix]
            );
        } else {
            // Append directories for an already registered namespace.
            $this->prefixDirsPsr4[$prefix] = array_merge(
                $this->prefixDirsPsr4[$prefix],
                $paths
            );
        }
    }
findFile()
findFile ($class)
Finds the path to the file where the class is defined.
Parameters
string $class The name of the class
Returns
string|false The path if found, false otherwise
Definition at line 442 of file ClassLoader.php.
    {
        // class map lookup
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }
        if ($this->classMapAuthoritative || isset($this->missingClasses[$class])) {
            return false;
        }
        if (null !== $this->apcuPrefix) {
            $file = apcu_fetch($this->apcuPrefix.$class, $hit);
            if ($hit) {
                return $file;
            }
        }
        $file = $this->findFileWithExtension($class, '.php');
        // Search for Hack files if we are running on HHVM
        if (false === $file && defined('HHVM_VERSION')) {
            $file = $this->findFileWithExtension($class, '.hh');
        }
        if (null !== $this->apcuPrefix) {
            apcu_add($this->apcuPrefix.$class, $file);
        }
        if (false === $file) {
            // Remember that this class does not exist.
            $this->missingClasses[$class] = true;
        }
        return $file;
    }
References ClassLoader\findFileWithExtension().
Referenced by ClassLoader\loadClass().
findFileWithExtension()
findFileWithExtension ($class, $ext) private
Parameters
string $class
string $ext
Returns
string|false
Definition at line 492 of file ClassLoader.php.
    {
        // PSR-4 lookup
        $logicalPathPsr4 = strtr($class, '\\', DIRECTORY_SEPARATOR) . $ext;
        $first = $class[0];
        if (isset($this->prefixLengthsPsr4[$first])) {
            $subPath = $class;
            while (false !== $lastPos = strrpos($subPath, '\\')) {
                $subPath = substr($subPath, 0, $lastPos);
                $search = $subPath . '\\';
                if (isset($this->prefixDirsPsr4[$search])) {
                    $pathEnd = DIRECTORY_SEPARATOR . substr($logicalPathPsr4, $lastPos + 1);
                    foreach ($this->prefixDirsPsr4[$search] as $dir) {
                        if (file_exists($file = $dir . $pathEnd)) {
                            return $file;
                        }
                    }
                }
            }
        }
        // PSR-4 fallback dirs
        foreach ($this->fallbackDirsPsr4 as $dir) {
            if (file_exists($file = $dir . DIRECTORY_SEPARATOR . $logicalPathPsr4)) {
                return $file;
            }
        }
        // PSR-0 lookup
        if (false !== $pos = strrpos($class, '\\')) {
            // namespaced class name
            $logicalPathPsr0 = substr($logicalPathPsr4, 0, $pos + 1)
                . strtr(substr($logicalPathPsr4, $pos + 1), '_', DIRECTORY_SEPARATOR);
        } else {
            // PEAR-like class name
            $logicalPathPsr0 = strtr($class, '_', DIRECTORY_SEPARATOR) . $ext;
        }
        if (isset($this->prefixesPsr0[$first])) {
            foreach ($this->prefixesPsr0[$first] as $prefix => $dirs) {
                if (0 === strpos($class, $prefix)) {
                    foreach ($dirs as $dir) {
                        if (file_exists($file = $dir . DIRECTORY_SEPARATOR . $logicalPathPsr0)) {
                            return $file;
                        }
                    }
                }
            }
        }
        // PSR-0 fallback dirs
        foreach ($this->fallbackDirsPsr0 as $dir) {
            if (file_exists($file = $dir . DIRECTORY_SEPARATOR . $logicalPathPsr0)) {
                return $file;
            }
        }
        // PSR-0 include paths.
        if ($this->useIncludePath && $file = stream_resolve_include_path($logicalPathPsr0)) {
            return $file;
        }
        return false;
    }
Referenced by ClassLoader\findFile().
getApcuPrefix()
getApcuPrefix ()
The APCu prefix in use, or null if APCu caching is not enabled.
Returns
string|null
Definition at line 375 of file ClassLoader.php.
    {
        return $this->apcuPrefix;
    }
References ClassLoader\$apcuPrefix.
getClassMap()
getClassMap ()
Returns
array<string, string> Array of classname => path
Definition at line 151 of file ClassLoader.php.
    {
        return $this->classMap;
    }
References ClassLoader\$classMap.
getFallbackDirs()
getFallbackDirs ()
Returns
list<string>
Definition at line 135 of file ClassLoader.php.
    {
        return $this->fallbackDirsPsr0;
    }
References ClassLoader\$fallbackDirsPsr0.
getFallbackDirsPsr4()
getFallbackDirsPsr4 ()
Returns
list<string>
Definition at line 143 of file ClassLoader.php.
    {
        return $this->fallbackDirsPsr4;
    }
References ClassLoader\$fallbackDirsPsr4.
getPrefixes()
getPrefixes ()
Returns
array<string, list<string>>
Definition at line 115 of file ClassLoader.php.
    {
        if (!empty($this->prefixesPsr0)) {
            return call_user_func_array('array_merge', array_values($this->prefixesPsr0));
        }
        return array();
    }
getPrefixesPsr4()
getPrefixesPsr4 ()
Returns
array<string, list<string>>
Definition at line 127 of file ClassLoader.php.
    {
        return $this->prefixDirsPsr4;
    }
References ClassLoader\$prefixDirsPsr4.
getRegisteredLoaders()
static getRegisteredLoaders () static
Returns the currently registered loaders keyed by their corresponding vendor directories.
Returns
array<string, self>
Definition at line 482 of file ClassLoader.php.
    {
        return self::$registeredLoaders;
    }
References ClassLoader\$registeredLoaders.
getUseIncludePath()
getUseIncludePath ()
Can be used to check if the autoloader uses the include path to check for classes.
Returns
bool
Definition at line 330 of file ClassLoader.php.
    {
        return $this->useIncludePath;
    }
References ClassLoader\$useIncludePath.
initializeIncludeClosure()
static initializeIncludeClosure () static private
Returns
void
Scope isolated include.
Prevents access to $this/self from included files.
Parameters
string $file
Returns
void
Definition at line 561 of file ClassLoader.php.
    {
        if (self::$includeFile !== null) {
            return;
        }
        self::$includeFile = \Closure::bind(static function($file) {
            include $file;
        }, null, null);
    }
Referenced by ClassLoader\__construct().
isClassMapAuthoritative()
isClassMapAuthoritative ()
Should class lookup fail if not found in the current class map?
Returns
bool
Definition at line 353 of file ClassLoader.php.
    {
        return $this->classMapAuthoritative;
    }
References ClassLoader\$classMapAuthoritative.
loadClass()
loadClass ($class)
Loads the given class or interface.
Parameters
string $class The name of the class
Returns
true|null True if loaded, null otherwise
Definition at line 423 of file ClassLoader.php.
    {
        if ($file = $this->findFile($class)) {
            $includeFile = self::$includeFile;
            $includeFile($file);
            return true;
        }
        return null;
    }
References ClassLoader\$includeFile, and ClassLoader\findFile().
register()
register ($prepend = false)
Registers this instance as an autoloader.
Parameters
bool $prepend Whether to prepend the autoloader or not
Returns
void
Definition at line 387 of file ClassLoader.php.
    {
        spl_autoload_register(array($this, 'loadClass'), true, $prepend);
        if (null === $this->vendorDir) {
            return;
        }
        if ($prepend) {
            self::$registeredLoaders = array($this->vendorDir => $this) + self::$registeredLoaders;
        } else {
            unset(self::$registeredLoaders[$this->vendorDir]);
            self::$registeredLoaders[$this->vendorDir] = $this;
        }
    }
References ClassLoader\$registeredLoaders, and ClassLoader\$vendorDir.
set()
set ($prefix, $paths)
Registers a set of PSR-0 directories for a given prefix, replacing any others previously set for this prefix.
Parameters
string $prefix The prefix
list<string>|string $paths The PSR-0 base directories
Returns
void
Definition at line 278 of file ClassLoader.php.
    {
        if (!$prefix) {
            $this->fallbackDirsPsr0 = (array) $paths;
        } else {
            $this->prefixesPsr0[$prefix[0]][$prefix] = (array) $paths;
        }
    }
setApcuPrefix()
setApcuPrefix ($apcuPrefix)
APCu prefix to use to cache found/not-found classes, if the extension is enabled.
Parameters
string | null $apcuPrefix
Returns
void
Definition at line 365 of file ClassLoader.php.
    {
        $this->apcuPrefix = function_exists('apcu_fetch') && filter_var(ini_get('apc.enabled'), FILTER_VALIDATE_BOOLEAN) ? $apcuPrefix : null;
    }
References ClassLoader\$apcuPrefix.
setClassMapAuthoritative()
setClassMapAuthoritative ($classMapAuthoritative)
Turns off searching the prefix and fallback directories for classes that have not been registered with the class map.
Parameters
bool $classMapAuthoritative
Returns
void
Definition at line 343 of file ClassLoader.php.
    {
        $this->classMapAuthoritative = $classMapAuthoritative;
    }
References ClassLoader\$classMapAuthoritative.
setPsr4()
setPsr4 ($prefix, $paths)
Registers a set of PSR-4 directories for a given namespace, replacing any others previously set for this namespace.
Parameters
string $prefix The prefix/namespace, with trailing '\'
list<string>|string $paths The PSR-4 base directories
Exceptions
InvalidArgumentException
Returns
void
Definition at line 298 of file ClassLoader.php.
    {
        if (!$prefix) {
            $this->fallbackDirsPsr4 = (array) $paths;
        } else {
            $length = strlen($prefix);
            if ('\\' !== $prefix[$length - 1]) {
                throw new \InvalidArgumentException("A non-empty PSR-4 prefix must end with a namespace separator.");
            }
            $this->prefixLengthsPsr4[$prefix[0]][$prefix] = $length;
            $this->prefixDirsPsr4[$prefix] = (array) $paths;
        }
    }
setUseIncludePath()
setUseIncludePath ($useIncludePath)
Turns on searching the include path for class files.
Parameters
bool $useIncludePath
Returns
void
Definition at line 319 of file ClassLoader.php.
    {
        $this->useIncludePath = $useIncludePath;
    }
References ClassLoader\$useIncludePath.
unregister()
unregister ()
Unregisters this instance as an autoloader.
Returns
void
Definition at line 408 of file ClassLoader.php.
    {
        spl_autoload_unregister(array($this, 'loadClass'));
        if (null !== $this->vendorDir) {
            unset(self::$registeredLoaders[$this->vendorDir]);
        }
    }
Field Documentation
$apcuPrefix
$apcuPrefix private
Definition at line 96 of file ClassLoader.php.
Referenced by ClassLoader\getApcuPrefix(), and ClassLoader\setApcuPrefix().
$classMap
$classMap = array() private
Definition at line 85 of file ClassLoader.php.
Referenced by ClassLoader\addClassMap(), and ClassLoader\getClassMap().
$classMapAuthoritative
$classMapAuthoritative = false private
Definition at line 88 of file ClassLoader.php.
Referenced by ClassLoader\isClassMapAuthoritative(), and ClassLoader\setClassMapAuthoritative().
$fallbackDirsPsr0
$fallbackDirsPsr0 = array() private
Definition at line 77 of file ClassLoader.php.
Referenced by ClassLoader\getFallbackDirs().
$fallbackDirsPsr4
$fallbackDirsPsr4 = array() private
Definition at line 63 of file ClassLoader.php.
Referenced by ClassLoader\getFallbackDirsPsr4().
$includeFile
$includeFile static private
Definition at line 46 of file ClassLoader.php.
Referenced by ClassLoader\loadClass().
$missingClasses
$missingClasses = array() private
Definition at line 93 of file ClassLoader.php.
$prefixDirsPsr4
$prefixDirsPsr4 = array() private
Definition at line 59 of file ClassLoader.php.
Referenced by ClassLoader\getPrefixesPsr4().
$prefixesPsr0
$prefixesPsr0 = array() private
Definition at line 73 of file ClassLoader.php.
$prefixLengthsPsr4
$prefixLengthsPsr4 = array() private
Definition at line 55 of file ClassLoader.php.
$registeredLoaders
$registeredLoaders = array() static private
Definition at line 101 of file ClassLoader.php.
Referenced by ClassLoader\getRegisteredLoaders(), and ClassLoader\register().
$useIncludePath
$useIncludePath = false private
Definition at line 80 of file ClassLoader.php.
Referenced by ClassLoader\getUseIncludePath(), and ClassLoader\setUseIncludePath().
$vendorDir
$vendorDir private
Definition at line 49 of file ClassLoader.php.
Referenced by ClassLoader\__construct(), and ClassLoader\register().