LGV_TZ_Lookup: CorruptedJsonListener Class Reference
CorruptedJsonListener Class Reference
Inherits ListenerInterface.
Public Member Functions
getJson ()
startDocument ()
endDocument ()
startArray ()
startObject ()
endArray ()
endObject ()
value ($value)
key (string $key)
whitespace (string $whitespace)
forceEndDocument ()
getKeys ()
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
Protected Attributes
$json
$stack
$keys
$level
Detailed Description
This implementation of a listener constructs an in-memory representation of the JSON document, this is useful to repair cut json documents (has unexpected end of the files).
Definition at line 12 of file CorruptedJsonListener.php.
Member Function Documentation
endArray()
endArray ()
Implements ListenerInterface.
Definition at line 54 of file CorruptedJsonListener.php.
                              : void
    {
        $this->endObject();
    }
References CorruptedJsonListener\endObject().
endDocument()
endDocument ()
Implements ListenerInterface.
Definition at line 39 of file CorruptedJsonListener.php.
                                 : void
    {
    }
endObject()
endObject ()
Implements ListenerInterface.
Definition at line 59 of file CorruptedJsonListener.php.
                               : void
    {
        $this->level--;
        $obj = array_pop($this->stack);
        if (empty($this->stack)) {
            // doc is DONE!
            $this->json = $obj;
        } else {
            $this->value($obj);
        }
    }
References CorruptedJsonListener\value().
Referenced by CorruptedJsonListener\endArray().
forceEndDocument()
forceEndDocument ()
Forcefully finish the document, end all objects and arrays and set final object to the json property.
Definition at line 100 of file CorruptedJsonListener.php.
                                      : void
    {
        if (empty($this->stack)) {
            return;
        }
        $key = $this->keys;
        for ($i = $this->level - 1; $i > 0; $i--) {
            $value = array_pop($this->stack);
            //value
            $obj = array_pop($this->stack);
            if (!empty($key[$i])) {
                $obj[$key[$i]] = $value;
                $key[$i] = null;
            } else {
                $obj[] = $value;
            }
            if ($i > 1) {
                $this->stack[] = $obj;
            } else {
                $this->json = $obj;
            }
        }
    }
References CorruptedJsonListener\$keys.
getJson()
getJson ()
Definition at line 25 of file CorruptedJsonListener.php.
    {
        return $this->json;
    }
References CorruptedJsonListener\$json.
getKeys()
getKeys ()
Return stack of keys before force ending documents.
Definition at line 128 of file CorruptedJsonListener.php.
                             : array
    {
        return $this->keys;
    }
References CorruptedJsonListener\$keys.
key()
key (string $key)
Implements ListenerInterface.
Definition at line 86 of file CorruptedJsonListener.php.
                                    : void
    {
        $this->keys[$this->level] = $key;
    }
References CorruptedJsonListener\$level.
startArray()
startArray ()
Implements ListenerInterface.
Definition at line 43 of file CorruptedJsonListener.php.
                                : void
    {
        $this->startObject();
    }
References CorruptedJsonListener\startObject().
startDocument()
startDocument ()
Implements ListenerInterface.
Definition at line 30 of file CorruptedJsonListener.php.
                                   : void
    {
        $this->stack = [];
        $this->level = 0;
        // Key is an array so that we can can remember keys per level to avoid
        // it being reset when processing child keys.
        $this->keys = [];
    }
startObject()
startObject ()
Implements ListenerInterface.
Definition at line 48 of file CorruptedJsonListener.php.
                                 : void
    {
        $this->level++;
        $this->stack[] = [];
    }
Referenced by CorruptedJsonListener\startArray().
value()
value ($value)
Value may be a string, integer, boolean, null.
Implements ListenerInterface.
Definition at line 74 of file CorruptedJsonListener.php.
                                 : void
    {
        $obj = array_pop($this->stack);
        if (!empty($this->keys[$this->level])) {
            $obj[$this->keys[$this->level]] = $value;
            $this->keys[$this->level] = null;
        } else {
            $obj[] = $value;
        }
        $this->stack[] = $obj;
    }
References CorruptedJsonListener\$level.
Referenced by CorruptedJsonListener\endObject().
whitespace()
whitespace (string $whitespace)
Implements ListenerInterface.
Definition at line 91 of file CorruptedJsonListener.php.
                                                  : void
    {
        // do nothing
    }
Field Documentation
$json
$json protected
Definition at line 14 of file CorruptedJsonListener.php.
Referenced by CorruptedJsonListener\getJson().
$keys
$keys protected
Definition at line 20 of file CorruptedJsonListener.php.
Referenced by CorruptedJsonListener\forceEndDocument(), and CorruptedJsonListener\getKeys().
$level
$level protected
Definition at line 23 of file CorruptedJsonListener.php.
Referenced by CorruptedJsonListener\key(), and CorruptedJsonListener\value().
$stack
$stack protected
Definition at line 16 of file CorruptedJsonListener.php.