LGV_TZ_Lookup: InMemoryListener Class Reference
InMemoryListener Class Reference
Inherits IdleListener.
Public Member Functions
getJson ()
startDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
Public Member Functions inherited from IdleListener
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
Protected Member Functions
startComplexValue ($type)
endComplexValue ()
insertValue ($value)
Protected Attributes
$result
$stack
$keys
Detailed Description
This basic implementation of a listener simply constructs an in-memory representation of the JSON document, which is a little silly since the whole point of a streaming parser is to avoid doing just that. However, it can serve as a starting point for more complex listeners, and illustrates some useful concepts for working with a streaming-style parser.
Definition at line 14 of file InMemoryListener.php.
Member Function Documentation
endArray()
endArray ()
Reimplemented from IdleListener.
Definition at line 54 of file InMemoryListener.php.
                              : void
    {
        $this->endComplexValue();
    }
References InMemoryListener\endComplexValue().
endComplexValue()
endComplexValue () protected
Definition at line 77 of file InMemoryListener.php.
                                        : void
    {
        $obj = array_pop($this->stack);
        // If the value stack is now empty, we're done parsing the document, so we can
        // move the result into place so that getJson() can return it. Otherwise, we
        // associate the value
        if (empty($this->stack)) {
            $this->result = $obj['value'];
        } else {
            $this->insertValue($obj['value']);
        }
    }
References InMemoryListener\insertValue().
Referenced by InMemoryListener\endArray(), and InMemoryListener\endObject().
endObject()
endObject ()
Reimplemented from IdleListener.
Definition at line 44 of file InMemoryListener.php.
                               : void
    {
        $this->endComplexValue();
    }
References InMemoryListener\endComplexValue().
getJson()
getJson ()
Definition at line 28 of file InMemoryListener.php.
    {
        return $this->result;
    }
References InMemoryListener\$result.
insertValue()
insertValue ($value) protected
Definition at line 93 of file InMemoryListener.php.
                                          : void
    {
        // Grab the top item from the stack that we're currently parsing.
        $currentItem = array_pop($this->stack);
        // Examine the current item, and then:
        //   - if it's an object, associate the newly-parsed value with the most recent key
        //   - if it's an array, push the newly-parsed value to the array
        if ('object' === $currentItem['type']) {
            $currentItem['value'][array_pop($this->keys)] = $value;
        } else {
            $currentItem['value'][] = $value;
        }
        // Replace the current item on the stack.
        $this->stack[] = $currentItem;
    }
Referenced by InMemoryListener\endComplexValue(), and InMemoryListener\value().
key()
key (string $key)
Reimplemented from IdleListener.
Definition at line 59 of file InMemoryListener.php.
                                    : void
    {
        $this->keys[] = $key;
    }
startArray()
startArray ()
Reimplemented from IdleListener.
Definition at line 49 of file InMemoryListener.php.
                                : void
    {
        $this->startComplexValue('array');
    }
References InMemoryListener\startComplexValue().
startComplexValue()
startComplexValue ($type) protected
Definition at line 69 of file InMemoryListener.php.
                                               : void
    {
        // We keep a stack of complex values (i.e. arrays and objects) as we build them,
        // tagged with the type that they are so we know how to add new values.
        $currentItem = ['type' => $type, 'value' => []];
        $this->stack[] = $currentItem;
    }
Referenced by InMemoryListener\startArray(), and InMemoryListener\startObject().
startDocument()
startDocument ()
Reimplemented from IdleListener.
Definition at line 33 of file InMemoryListener.php.
                                   : void
    {
        $this->stack = [];
        $this->keys = [];
    }
startObject()
startObject ()
Reimplemented from IdleListener.
Definition at line 39 of file InMemoryListener.php.
                                 : void
    {
        $this->startComplexValue('object');
    }
References InMemoryListener\startComplexValue().
value()
value ($value)
Parameters
mixed $value the value as read from the parser, it may be a string, integer, boolean, etc
Reimplemented from IdleListener.
Definition at line 64 of file InMemoryListener.php.
                                 : void
    {
        $this->insertValue($value);
    }
References InMemoryListener\insertValue().
Field Documentation
$keys
$keys protected
Definition at line 26 of file InMemoryListener.php.
$result
$result protected
Definition at line 16 of file InMemoryListener.php.
Referenced by InMemoryListener\getJson().
$stack
$stack protected
Definition at line 21 of file InMemoryListener.php.