LGV_TZ_Lookup: SimpleObjectQueueListener Class Reference
SimpleObjectQueueListener Class Reference
Inherits ListenerInterface.
Public Member Functions
__construct (callable $callback=null, int $returnType=self::TYPE_ARRAY)
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
Data Fields
const TYPE_ARRAY = 1
const TYPE_OBJECT = 2
Protected Member Functions
reset ()
Protected Attributes
$currentObject = []
$currentKey
$callback
$returnType
Detailed Description
This listener is for parsing very simple JSON files that contain an array of objects. For example [{"id":"1", "name":"foo"}, {"id","2","name":"bar"}] This can be useful for seeding databases or importing massive amounts of data. Please do note that is intended for single level simple objects. To support nested objects you need to modify the code as suited to your purposes.
Definition at line 14 of file SimpleObjectQueueListener.php.
Constructor & Destructor Documentation
__construct()
__construct (callable $callback = null, int $returnType = self::TYPE_ARRAY)
Initiate the listener for very simple objects that do not contain nested elements. For example [{"id":"1", "name":"foo"}, {"id","2","name":"bar"}].
Parameters
callable $callback
int $returnType one
type to callback. Defaults to to associative array.
SimpleObjectQueueListener::TYPE_ARRAY will provide an associative array to the callback
SimpleObjectQueueListener::TYPE_OBJECT will privde an object to the callback
Definition at line 50 of file SimpleObjectQueueListener.php.
    {
        $this->returnType = $returnType;
        $this->callback = $callback;
    }
References SimpleObjectQueueListener\$callback, and SimpleObjectQueueListener\$returnType.
Member Function Documentation
endArray()
endArray ()
Implements ListenerInterface.
Definition at line 90 of file SimpleObjectQueueListener.php.
                              : void
    {
        /* no need to support arrays */
    }
endDocument()
endDocument ()
Implements ListenerInterface.
Definition at line 61 of file SimpleObjectQueueListener.php.
                                 : void
    {
        $this->reset();
    }
References SimpleObjectQueueListener\reset().
endObject()
endObject ()
Implements ListenerInterface.
Definition at line 71 of file SimpleObjectQueueListener.php.
                               : void
    {
        /*
         * Return the currently compiled object to the callback.
         */
        if (self::TYPE_ARRAY === $this->returnType) {
            \call_user_func($this->callback, $this->currentObject);
        } elseif (self::TYPE_OBJECT === $this->returnType) {
            \call_user_func($this->callback, (object) $this->currentObject);
        } else {
            throw new \Exception('Unsupported callback data type requested.');
        }
    }
key()
key (string $key)
Implements ListenerInterface.
Definition at line 95 of file SimpleObjectQueueListener.php.
                                    : void
    {
        $this->currentKey = $key;
    }
reset()
reset () protected
Reset all the values to default.
Definition at line 112 of file SimpleObjectQueueListener.php.
                              : void
    {
        $this->currentObject = [];
        $this->currentKey = null;
    }
Referenced by SimpleObjectQueueListener\endDocument(), SimpleObjectQueueListener\startDocument(), and SimpleObjectQueueListener\startObject().
startArray()
startArray ()
Implements ListenerInterface.
Definition at line 85 of file SimpleObjectQueueListener.php.
                                : void
    {
        /* we support an array of objects, not nested arrays. leave this alone */
    }
startDocument()
startDocument ()
Implements ListenerInterface.
Definition at line 56 of file SimpleObjectQueueListener.php.
                                   : void
    {
        $this->reset();
    }
References SimpleObjectQueueListener\reset().
startObject()
startObject ()
Implements ListenerInterface.
Definition at line 66 of file SimpleObjectQueueListener.php.
                                 : void
    {
        $this->reset();
    }
References SimpleObjectQueueListener\reset().
value()
value ($value)
Parameters
mixed $value the value as read from the parser, it may be a string, integer, boolean, etc
Implements ListenerInterface.
Definition at line 100 of file SimpleObjectQueueListener.php.
                                 : void
    {
        $this->currentObject[$this->currentKey] = $value;
    }
References SimpleObjectQueueListener\$currentKey.
whitespace()
whitespace (string $whitespace)
Implements ListenerInterface.
Definition at line 105 of file SimpleObjectQueueListener.php.
                                                  : void
    {
    }
Field Documentation
$callback
$callback protected
Definition at line 32 of file SimpleObjectQueueListener.php.
Referenced by SimpleObjectQueueListener\__construct().
$currentKey
$currentKey protected
Definition at line 27 of file SimpleObjectQueueListener.php.
Referenced by SimpleObjectQueueListener\value().
$currentObject
$currentObject = [] protected
Definition at line 22 of file SimpleObjectQueueListener.php.
$returnType
$returnType protected
Definition at line 37 of file SimpleObjectQueueListener.php.
Referenced by SimpleObjectQueueListener\__construct().
TYPE_ARRAY
const TYPE_ARRAY = 1
Definition at line 16 of file SimpleObjectQueueListener.php.
TYPE_OBJECT
const TYPE_OBJECT = 2
Definition at line 17 of file SimpleObjectQueueListener.php.