LGV_TZ_Lookup: SubsetConsumerListener Class Reference
SubsetConsumerListener Class Reference
Inherits ListenerInterface.
Public Member Functions
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
startDocument ()
endDocument ()
startObject ()
endObject ()
startArray ()
endArray ()
key (string $key)
value ($value)
whitespace (string $whitespace)
Protected Member Functions
consume ($data)
Protected Attributes
$keyValueStack
$key
Detailed Description
Definition at line 7 of file SubsetConsumerListener.php.
Member Function Documentation
consume()
consume ($data) abstract protected
Returns
bool if data was consumed and can be discarded
Referenced by SubsetConsumerListener\endObject().
endArray()
endArray ()
Implements ListenerInterface.
Definition at line 48 of file SubsetConsumerListener.php.
                              : void
    {
        $this->endObject();
    }
References SubsetConsumerListener\endObject().
endDocument()
endDocument ()
Implements ListenerInterface.
Definition at line 21 of file SubsetConsumerListener.php.
                                 : void
    {
    }
endObject()
endObject ()
Implements ListenerInterface.
Definition at line 31 of file SubsetConsumerListener.php.
                               : void
    {
        $keyValue = array_pop($this->keyValueStack);
        $obj = reset($keyValue);
        $this->key = key($keyValue);
        $hasBeenConsumed = $this->consume($obj);
        if (!empty($this->keyValueStack)) {
            $this->value($hasBeenConsumed ? '*consumed*' : $obj);
        }
    }
References SubsetConsumerListener\consume(), SubsetConsumerListener\key(), and SubsetConsumerListener\value().
Referenced by SubsetConsumerListener\endArray().
key()
key (string $key)
Implements ListenerInterface.
Definition at line 53 of file SubsetConsumerListener.php.
                                    : void
    {
        $this->key = $key;
    }
References SubsetConsumerListener\$key, and SubsetConsumerListener\key().
Referenced by SubsetConsumerListener\endObject(), SubsetConsumerListener\key(), SubsetConsumerListener\startObject(), and SubsetConsumerListener\value().
startArray()
startArray ()
Implements ListenerInterface.
Definition at line 43 of file SubsetConsumerListener.php.
                                : void
    {
        $this->startObject();
    }
References SubsetConsumerListener\startObject().
startDocument()
startDocument ()
Implements ListenerInterface.
Definition at line 16 of file SubsetConsumerListener.php.
                                   : void
    {
        $this->keyValueStack = [];
    }
startObject()
startObject ()
Implements ListenerInterface.
Definition at line 25 of file SubsetConsumerListener.php.
                                 : void
    {
        $this->keyValueStack[] = null === $this->key ? [[]] : [$this->key => []];
        $this->key = null;
    }
References SubsetConsumerListener\key().
Referenced by SubsetConsumerListener\startArray().
value()
value ($value)
Parameters
mixed $value the value as read from the parser, it may be a string, integer, boolean, etc
Implements ListenerInterface.
Definition at line 58 of file SubsetConsumerListener.php.
                                 : void
    {
        $keyValue = array_pop($this->keyValueStack);
        $objKey = key($keyValue);
        if ($this->key) {
            $keyValue[$objKey][$this->key] = $value;
        } else {
            $keyValue[$objKey][] = $value;
        }
        $this->keyValueStack[] = $keyValue;
    }
References SubsetConsumerListener\$key, and SubsetConsumerListener\key().
Referenced by SubsetConsumerListener\endObject().
whitespace()
whitespace (string $whitespace)
Implements ListenerInterface.
Definition at line 71 of file SubsetConsumerListener.php.
                                                  : void
    {
    }
Field Documentation
$key
$key protected
Definition at line 14 of file SubsetConsumerListener.php.
Referenced by SubsetConsumerListener\key(), and SubsetConsumerListener\value().
$keyValueStack
$keyValueStack protected
Definition at line 9 of file SubsetConsumerListener.php.